a= input('escreva algo:')
print('O tipo permitivo deste valor é',type(a))
print('Só tem espaço?',a.isspace())
print('É um número?',a.isnumeric())
print('É alfabeto? ',a.isalpha())
print('É alfanumérico? ',a.isalnum())
print('Está em maiúscula? ',a.isupper())
print('Está em minúscula? ',a.islower())
print('Está capitalizada? ',a.istitle())